# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
title: Generating high-quanlity symbolic music using fine-grained discriminators
description: The official examples and supplement materials of article "Generating high-quanlity symbolic music using fine-grained discriminators"

